# SQLite version 3.x --> Change PostgreSQL(after git clone)
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mof_work_development

test:
  <<: *default
  database: mof_work_test

production:
  <<: *default
  database: mof_work_production
  username: mof_work
  password: <%= ENV['MOF_WORK_DATABASE_PASSWORD'] %>